In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_arr.shape

(1000000,)

In [6]:
my_arr[100]

100

In [7]:
my_list = list(range(1000000))

In [8]:
my_list[100]

100

In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.7 ms, sys: 20.2 ms, total: 37.9 ms
Wall time: 41.3 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 618 ms, sys: 174 ms, total: 792 ms
Wall time: 800 ms


In [11]:
data = np.random.randn(2, 3)

In [12]:
data

array([[-0.31434604, -1.22324782,  1.12319742],
       [-1.85756301,  0.47360231,  0.76131137]])

In [13]:
data * 10

array([[ -3.14346035, -12.2324782 ,  11.23197424],
       [-18.57563015,   4.73602315,   7.61311371]])

In [14]:
data + data

array([[-0.62869207, -2.44649564,  2.24639485],
       [-3.71512603,  0.94720463,  1.52262274]])

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
data1 = [6, 7.5, 8, 0, 1]

In [18]:
arr1 = np.array(data1)

In [19]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [20]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int64')

In [27]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [28]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
np.empty((2, 3, 2))

array([[[  2.00000000e+000,   2.00000000e+000],
        [  2.96439388e-323,   9.88131292e-324],
        [  0.00000000e+000,   1.16095442e-028]],

       [[  0.00000000e+000,   3.68008723e-110],
        [  0.00000000e+000,   3.67145744e+228],
        [  0.00000000e+000,   9.02425802e-309]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr1 = np.arange(15, dtype=np.float64)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr2.dtype

dtype('int32')

In [36]:
float_arr = arr2.astype(np.float64)

In [37]:
float_arr.dtype

dtype('float64')

In [38]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [39]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [40]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [50]:
arr2 = numeric_strings.astype(np.float64)

In [51]:
arr2.astype(np.int32)

array([ 1, -9, 42], dtype=int32)

In [52]:
int_array = np.arange(10)

In [53]:
int_array.dtype

dtype('int64')

In [54]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [55]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [56]:
empty_uint32 = np.empty(8, dtype='u4')

In [57]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [60]:
arr = np.array(([1., 2., 3.], [4., 5., 6.]))

In [61]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [62]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [63]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [64]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [65]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [66]:
arr = np.arange(10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[0]

0

In [74]:
arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
arr[2:8] = np.arange(6)

In [76]:
arr

array([0, 1, 0, 1, 2, 3, 4, 5, 8, 9])

In [82]:
arr_slice = arr[5:8]

In [83]:
arr_slice

array([3, 4, 5])

In [86]:
arr_slice[0] = 24

In [87]:
arr

array([ 0,  1,  0,  1,  2, 24,  4, 24,  8,  9])

In [88]:
arr_slice2 = arr[5:8].copy()

In [89]:
arr_slice2

array([24,  4, 24])

In [90]:
arr_slice2[0] = 7

In [91]:
arr

array([ 0,  1,  0,  1,  2, 24,  4, 24,  8,  9])

In [92]:
arr_slice2

array([ 7,  4, 24])

In [93]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr2d[2]

array([7, 8, 9])

In [96]:
arr2d[2,1]

8

In [97]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [98]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr3d[1,0] 

array([7, 8, 9])

In [107]:
arr3d[1,0] = arr2d[0]

In [108]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [10, 11, 12]]])

In [109]:
arr3d.dtype

dtype('int64')

In [110]:
arr3d.shape

(2, 2, 3)

In [111]:
arr[1:6]

array([ 1,  0,  1,  2, 24])

In [112]:
arr

array([ 0,  1,  0,  1,  2, 24,  4, 24,  8,  9])

In [113]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [117]:
arr2d[1, :2]

array([4, 5])

In [118]:
arr2d[2, :1]

array([7])

In [119]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [122]:
arr2d[:3, 1:] = 5

In [123]:
arr2d

array([[1, 5, 5],
       [4, 5, 5],
       [7, 5, 5]])

In [124]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [125]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [126]:
data = np.random.randn(7, 4)

In [134]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [135]:
data[names == 'Bob']

array([[-0.88988477,  0.01635202,  0.20298541, -0.20869657],
       [ 0.72405968, -0.99578486,  0.55386544,  0.92892944]])

In [136]:
data

array([[-0.88988477,  0.01635202,  0.20298541, -0.20869657],
       [ 1.13700484, -0.71105651,  1.4683575 , -0.11409487],
       [-0.00374372, -0.61868498, -0.44082051, -0.39734402],
       [ 0.72405968, -0.99578486,  0.55386544,  0.92892944],
       [ 0.02991474,  0.59567453, -1.57188923,  1.83607467],
       [-0.75995803,  1.40518894,  1.28414339,  0.30194909],
       [-0.32761921,  0.37584982, -0.81062031, -0.22443643]])

In [137]:
data[names == 'Bob', 2:]

array([[ 0.20298541, -0.20869657],
       [ 0.55386544,  0.92892944]])

In [138]:
data[names == 'Bob', 3]

array([-0.20869657,  0.92892944])

In [141]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [142]:
data[~(names == 'Bob')]

array([[ 1.13700484, -0.71105651,  1.4683575 , -0.11409487],
       [-0.00374372, -0.61868498, -0.44082051, -0.39734402],
       [ 0.02991474,  0.59567453, -1.57188923,  1.83607467],
       [-0.75995803,  1.40518894,  1.28414339,  0.30194909],
       [-0.32761921,  0.37584982, -0.81062031, -0.22443643]])

In [143]:
mask = (names == 'Bob') | (names == 'Will')

In [144]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [145]:
data[mask]

array([[-0.88988477,  0.01635202,  0.20298541, -0.20869657],
       [-0.00374372, -0.61868498, -0.44082051, -0.39734402],
       [ 0.72405968, -0.99578486,  0.55386544,  0.92892944],
       [ 0.02991474,  0.59567453, -1.57188923,  1.83607467]])

In [146]:
data[data < 0] = 0

In [147]:
data

array([[ 0.        ,  0.01635202,  0.20298541,  0.        ],
       [ 1.13700484,  0.        ,  1.4683575 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.72405968,  0.        ,  0.55386544,  0.92892944],
       [ 0.02991474,  0.59567453,  0.        ,  1.83607467],
       [ 0.        ,  1.40518894,  1.28414339,  0.30194909],
       [ 0.        ,  0.37584982,  0.        ,  0.        ]])

In [148]:
data[names != 'Joe'] = 7

In [149]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.13700484,  0.        ,  1.4683575 ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  1.40518894,  1.28414339,  0.30194909],
       [ 0.        ,  0.37584982,  0.        ,  0.        ]])

In [150]:
arr = np.empty((8, 4))

In [152]:
for i in range(8):
   .....:     arr[i] = i

In [155]:
arr = arr*2

In [156]:
arr

array([[  0.,   0.,   0.,   0.],
       [  2.,   2.,   2.,   2.],
       [  4.,   4.,   4.,   4.],
       [  6.,   6.,   6.,   6.],
       [  8.,   8.,   8.,   8.],
       [ 10.,  10.,  10.,  10.],
       [ 12.,  12.,  12.,  12.],
       [ 14.,  14.,  14.,  14.]])

In [157]:
arr[[4, 3, 0, 6]]

array([[  8.,   8.,   8.,   8.],
       [  6.,   6.,   6.,   6.],
       [  0.,   0.,   0.,   0.],
       [ 12.,  12.,  12.,  12.]])

In [158]:
arr[[-3, -5, -7]]

array([[ 10.,  10.,  10.,  10.],
       [  6.,   6.,   6.,   6.],
       [  2.,   2.,   2.,   2.]])

In [159]:
arr = np.arange(32).reshape((8, 4))

In [160]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [161]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [162]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [163]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [164]:
arr = np.arange(15).reshape((3, 5))

In [165]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [167]:
arr = np.random.randn(6, 3)

In [168]:
np.dot(arr.T, arr)

array([[  5.89308198,  -3.50112895,   2.24992673],
       [ -3.50112895,   9.67504897,   1.12820812],
       [  2.24992673,   1.12820812,  15.68135463]])

In [169]:
arr = np.arange(16).reshape((2, 2, 4))

In [170]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [171]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [172]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])