In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# Chapter 7. Data Cleaning and Preparation

# Handling Missing Data

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

# Filtering Out Missing Data

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [9]:
data.dropna() # On a Series, it returns the Series with only the non-null data and index values

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()] # equivalent to dropna

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
   ....:                      [NA, NA, NA], [NA, 6.5, 3.]])

In [12]:
cleaned = data.dropna() # in DataFrame dropna by default drops any row containing a missing value

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all') # to only drop rows that are all NA:

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1, how='all') # to drop columns

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.randn(7, 3))

In [20]:
df.iloc[:4, 1] = NA; df.iloc[:2, 2] = NA

In [21]:
df

0         1         2
0 -1.568060       NaN       NaN
1 -0.191239       NaN       NaN
2  0.372937       NaN  0.390717
3 -0.198557       NaN  2.138960
4 -1.069003 -0.327112  0.285551
5  0.384270  0.698447  0.187420
6  0.670072  0.866528  0.021395

In [22]:
df.dropna(thresh=2) # you want to keep only rows containing a certain number of observations.

0         1         2
2  0.372937       NaN  0.390717
3 -0.198557       NaN  2.138960
4 -1.069003 -0.327112  0.285551
5  0.384270  0.698447  0.187420
6  0.670072  0.866528  0.021395

In [23]:
383/812

0.47167487684729065

# Filling in Missing Data

In [24]:
df.fillna(0) # filling missing values with a constant

0         1         2
0 -1.568060  0.000000  0.000000
1 -0.191239  0.000000  0.000000
2  0.372937  0.000000  0.390717
3 -0.198557  0.000000  2.138960
4 -1.069003 -0.327112  0.285551
5  0.384270  0.698447  0.187420
6  0.670072  0.866528  0.021395

In [25]:
df.fillna({1: 0.5, 3: -1, 2: 0}) # filling with a different value in each column

0         1         2
0 -1.568060  0.500000  0.000000
1 -0.191239  0.500000  0.000000
2  0.372937  0.500000  0.390717
3 -0.198557  0.500000  2.138960
4 -1.069003 -0.327112  0.285551
5  0.384270  0.698447  0.187420
6  0.670072  0.866528  0.021395

In [26]:
_ = df.fillna(0, inplace=True) # fillna returns a new object, but you can modify the existing object in place:

In [27]:
df

0         1         2
0 -1.568060  0.000000  0.000000
1 -0.191239  0.000000  0.000000
2  0.372937  0.000000  0.390717
3 -0.198557  0.000000  2.138960
4 -1.069003 -0.327112  0.285551
5  0.384270  0.698447  0.187420
6  0.670072  0.866528  0.021395

In [28]:
df = pd.DataFrame(np.random.randn(6, 3))

In [29]:
df.iloc[2:, 1] = NA; df.iloc[4:, 2] = NA

In [30]:
df

0         1         2
0 -0.802222 -0.632627 -1.014385
1  0.386626  0.300354  1.965942
2 -1.510466       NaN -0.879601
3  0.058761       NaN -2.104585
4  0.860706       NaN       NaN
5  0.826360       NaN       NaN

In [31]:
df.fillna(method='ffill') # filling with the last value columnwise

0         1         2
0 -0.802222 -0.632627 -1.014385
1  0.386626  0.300354  1.965942
2 -1.510466  0.300354 -0.879601
3  0.058761  0.300354 -2.104585
4  0.860706  0.300354 -2.104585
5  0.826360  0.300354 -2.104585

In [32]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.802222 -0.632627 -1.014385
1  0.386626  0.300354  1.965942
2 -1.510466  0.300354 -0.879601
3  0.058761  0.300354 -2.104585
4  0.860706       NaN -2.104585
5  0.826360       NaN -2.104585

In [33]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [34]:
data.fillna(data.mean()) # to fill with the mean value

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Data Transformation

# Removing Duplicates

In [36]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
   ....:                      'k2': [1, 1, 2, 3, 3, 4, 4]})

In [37]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [38]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [39]:
data1 = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
   ....:                      'k2': [1, 1, 2, 4, 3, 4, 3]})

In [40]:
data1

k1  k2
0  one   1
1  one   1
2  one   2
3  two   4
4  two   3
5  two   4
6  two   3

In [41]:
data1.duplicated()

0    False
1     True
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [42]:
data1.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   4
4  two   3

In [43]:
data['v1'] = range(7)

In [44]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [45]:
data.drop_duplicates(['k1', 'k2'], keep='last') # to find duplicates based on two columns and to keep the last value

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

# Transforming Data Using a Function or Mapping

In [46]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
   ....:                               'corned beef', 'Bacon', 'pastrami', 'honey ham',
   ....:                               'nova lox'],
   ....:                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [49]:
# to add a column indicating the type of animal that each food came from.
# converting first each value to lower case (only for mapping, not in the original data)
data['animal'] = data['food'].str.lower().map(meat_to_animal) 

In [50]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [51]:
# It is also possible to pass a function that does all the work:

data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [53]:
data.drop(['animal'], axis = 1)

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [54]:
data['animal'] = data['food'].map(lambda x: meat_to_animal[x.lower()])

In [55]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

# Replacing Values

In [56]:
# While map can be used to modify a subset of values in an object, 
# replace provides a simpler and more flexible way to do so. 

data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [57]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
# can also be a dict
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

In [61]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
   ....:                     index=['Ohio', 'Colorado', 'New York'],
   ....:                     columns=['one', 'two', 'three', 'four'])

In [62]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [63]:
# to cut four letters and to make them upper case
transform = lambda x: x[:4].upper()

In [64]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [66]:
# to transform in place
data.index = data.index.map(transform)

In [67]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [68]:
# to create a transformed version of a data set without modifying the original:

data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [69]:
data.rename(columns=str.upper)

ONE  TWO  THREE  FOUR
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [70]:
data.rename(index={'OHIO': 'INDIANA'},
   ....:             columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [71]:
# to modify a data set in place:

data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [72]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

# Discretization and Binning

In [74]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [75]:
# to divide these into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older:
bins = [18, 25, 35, 60, 100]

In [76]:
cats = pd.cut(ages, bins)

In [77]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [78]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [79]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [80]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [81]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [82]:
# to pass your own bin names by passing a list or array to the labels option:

group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [83]:
# to compute equal-length bins based on the minimum and maximum values in the data:

data = np.random.rand(20)

pd.cut(data, 4, precision=2)

[(0.075, 0.3], (0.76, 0.99], (0.075, 0.3], (0.53, 0.76], (0.075, 0.3], ..., (0.76, 0.99], (0.76, 0.99], (0.76, 0.99], (0.53, 0.76], (0.3, 0.53]]
Length: 20
Categories (4, interval[float64]): [(0.075, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 0.99]]

In [84]:
pd.value_counts(pd.cut(data, 4, precision=2))

(0.76, 0.99]    7
(0.3, 0.53]     5
(0.075, 0.3]    5
(0.53, 0.76]    3
dtype: int64

In [85]:
# to bin the data based on sample quantiles:

data = np.random.randn(1000)  # Normally distributed

In [89]:
pd.value_counts(pd.qcut(data, 4))

(0.706, 2.951]      250
(0.0613, 0.706]     250
(-0.603, 0.0613]    250
(-3.021, -0.603]    250
dtype: int64

In [90]:
pd.value_counts(pd.cut(data, 4))

(-0.0346, 1.458]     464
(-1.527, -0.0346]    409
(1.458, 2.951]        70
(-3.026, -1.527]      57
dtype: int64

In [92]:
pd.value_counts(pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]))

(0.0613, 1.315]    400
(-1.22, 0.0613]    400
(1.315, 2.951]     100
(-3.021, -1.22]    100
dtype: int64

# Detecting and Filtering Outliers

In [93]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [94]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004005    -0.061143    -0.016069    -0.009928
std       1.008442     1.007326     1.011195     1.024437
min      -3.547369    -3.393104    -3.000387    -2.821050
25%      -0.653165    -0.713718    -0.648565    -0.732338
50%       0.008717    -0.057484    -0.046276    -0.032686
75%       0.667600     0.618211     0.679866     0.675964
max       2.995772     3.031677     2.881956     3.420574

In [97]:
col = data[0]

In [98]:
col[np.abs(col) > 3]

126   -3.171874
481   -3.547369
537   -3.157029
570   -3.447790
770   -3.084872
Name: 0, dtype: float64

In [101]:
# To select all rows having a value exceeding 3 or -3:

data[(np.abs(data) > 3).any(1)]

0         1         2         3
29  -0.488818 -3.331596  0.581790 -0.243568
98  -1.229142 -3.393104 -0.950178 -0.594127
126 -3.171874 -0.328653 -0.279155  0.181817
256 -0.600181  3.031677  0.041864  0.558180
481 -3.547369 -1.660374 -0.456769  1.737703
537 -3.157029  1.304251  0.644318 -2.047424
570 -3.447790 -0.261705 -2.210310 -0.860826
597  0.267899 -0.551171 -0.198158  3.420574
770 -3.084872  2.833761 -1.976009  0.158761
832 -0.286576 -0.411503 -3.000387 -0.500636
985 -0.738009 -3.100152  0.037669 -1.996375

In [108]:
# to select rows based only on the first column
data[np.abs(col) > 3]

0         1         2         3
126 -3.171874 -0.328653 -0.279155  0.181817
481 -3.547369 -1.660374 -0.456769  1.737703
537 -3.157029  1.304251  0.644318 -2.047424
570 -3.447790 -0.261705 -2.210310 -0.860826
770 -3.084872  2.833761 -1.976009  0.158761

In [109]:
# to cap values outside the interval -3 to 3 (np.sign returns an array of 1 and -1 depending on the sign of the values):
data[np.abs(data) > 3] = np.sign(data) * 3

In [110]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002596    -0.060350    -0.016068    -0.010349
std       1.003962     1.004680     1.011194     1.023113
min      -3.000000    -3.000000    -3.000000    -2.821050
25%      -0.653165    -0.713718    -0.648565    -0.732338
50%       0.008717    -0.057484    -0.046276    -0.032686
75%       0.667600     0.618211     0.679866     0.675964
max       2.995772     3.000000     2.881956     3.000000

# Permutation and Random Sampling

In [111]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [112]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [113]:
# Calling permutation with the length of the axis you want to permute (randomly reordering) produces 
# an array of integers indicating the new ordering:

sampler = np.random.permutation(5)

In [114]:
sampler

array([3, 4, 0, 2, 1])

In [115]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7

In [116]:
# To select a random subset without replacement, one way is to slice 
# off the first k elements of the array returned by permutation, where k is the desired subset size.

df.take(np.random.permutation(len(df))[:3])

0   1   2   3
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11

In [117]:
bag = np.array([5, 7, -1, 6, 4])

In [118]:
# To generate a sample with replacement, the fastest way is to use np.random.randint to draw random integers:

sampler = np.random.randint(0, len(bag), size=10)

In [119]:
sampler

array([3, 0, 2, 1, 3, 4, 2, 1, 1, 2])

In [120]:
draws = bag.take(sampler)

In [121]:
draws

array([ 6,  5, -1,  7,  6,  4, -1,  7,  7, -1])

# Computing Indicator/Dummy Variables

In [122]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
   .....:                    'data1': range(6)})

In [123]:
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [124]:
# converting a categorical variable into a “dummy” or “indicator” matrix. If a column in a DataFrame 
# has k distinct values, you would derive a matrix or DataFrame containing k columns containing all 1’s and 0’s.
# 1 if the specified "key" value appeared in the row, that is one 1 in each row

pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [125]:
# to add a prefix to the columns in the indicator DataFrame, which can then be merged with the other data:

dummies = pd.get_dummies(df['key'], prefix='key')

In [126]:
df_with_dummy = df[['data1']].join(dummies)

In [127]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [128]:
# If a row in a DataFrame belongs to multiple categories, things are a bit more complicated:

mnames = ['movie_id', 'title', 'genres']

In [130]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None,
   .....:                         names=mnames)

/Users/sharon/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [131]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [132]:
# Adding indicator variables for each genre requires a little bit of wrangling. 
# First, we extract the list of unique genres in the dataset:

all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [133]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [134]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [136]:
zero_matrix.shape

(3883, 18)

In [137]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [139]:
gen = movies.genres[0]

In [140]:
gen

"Animation|Children's|Comedy"

In [141]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [142]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [143]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [144]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [145]:
movies_windic[:10]

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   
5         6                         Heat (1995)         Action|Crime|Thriller   
6         7                      Sabrina (1995)                Comedy|Romance   
7         8                 Tom and Huck (1995)          Adventure|Children's   
8         9                 Sudden Death (1995)                        Action   
9        10                    GoldenEye (1995)     Action|Adventure|Thriller   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   
5              0.0               0.0           0.0              0.0   
6              0.0               0.0           1.0              0.0   
7              0.0               1.0           0.0              1.0   
8              0.0               0.0           0.0              0.0   
9              0.0               0.0           0.0              1.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama      ...        Genre_Crime  \
0            0.0            0.0          0.0      ...                0.0   
1            1.0            0.0          0.0      ...                0.0   
2            0.0            1.0          0.0      ...                0.0   
3            0.0            0.0          1.0      ...                0.0   
4            0.0            0.0          0.0      ...                0.0   
5            0.0            0.0          0.0      ...                1.0   
6            0.0            1.0          0.0      ...                0.0   
7            0.0            0.0          0.0      ...                0.0   
8            0.0            0.0          0.0      ...                0.0   
9            0.0            0.0          0.0      ...                0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   
5             1.0           0.0           0.0                0.0        0.0   
6             0.0           0.0           0.0                0.0        0.0   
7             0.0           0.0           0.0                0.0        0.0   
8             0.0           0.0           0.0                0.0        0.0   
9             1.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  
5            0.0            0.0              0.0            0.0  
6            0.0            0.0              0.0            0.0  
7            0.0            0.0              0.0            0.0  
8            0.0            

0.5024630541871922