In [3]:
import pandas as pd
import numpy as np

In [4]:
from pandas import Series, DataFrame

# Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [17]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3 # is ordered by indeces

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [29]:
states = ['California', 'Texas', 'Oregon', 'Ohio'] # to override ordering 

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Texas         71000.0
Oregon        16000.0
Ohio          35000.0
dtype: float64

In [32]:
pd.isnull(obj4)

California     True
Texas         False
Oregon        False
Ohio          False
dtype: bool

In [33]:
pd.notnull(obj4)

California    False
Texas          True
Oregon         True
Ohio           True
dtype: bool

In [34]:
obj4.isnull()

California     True
Texas         False
Oregon        False
Ohio          False
dtype: bool

In [35]:
obj3 + obj4 # if an index doesn't appear in one of the series it will be Nan. Is sorted

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
obj4.name = 'population'

In [37]:
obj4.index.name = 'state'

In [38]:
obj4

state
California        NaN
Texas         71000.0
Oregon        16000.0
Ohio          35000.0
Name: population, dtype: float64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)

In [42]:
frame # columns are sorted by their names

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [43]:
frame.head() # shows first 5 rows

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # to specify the order

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [46]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
   ....:                       index=['one', 'two', 'three', 'four', 'five'])

In [47]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2['state'] # each column is a Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [51]:
frame2.loc['three'] # to retrieve a row

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [56]:
frame2['debt'] = np.arange(5.)

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
frame2['debt'] = val

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [61]:
frame2['eastern'] = frame2.state == 'Ohio'

In [62]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [63]:
del frame2['eastern']

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [66]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
   ....:        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
frame3 = pd.DataFrame(pop)

In [68]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [70]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [83]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]} # equivalent [:2], [:-1]

In [84]:
pdata

{'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [85]:
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [86]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [87]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

# Index Objects

In [92]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [93]:
index = obj.index

In [94]:
index

Index(['a', 'b', 'c'], dtype='object')

In [95]:
index[1:]

Index(['b', 'c'], dtype='object')

In [96]:
index[1] = 'd' #Index objects are immutable and thus can’t be modified by the user:

TypeError: Index does not support mutable operations

In [97]:
index = pd.Index(np.arange(3))

In [98]:
obj2 = pd.Series([1.5, -2.5, 0], index=index)

In [99]:
obj2.index is index

True

In [100]:
index

Int64Index([0, 1, 2], dtype='int64')

In [101]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [102]:
'Ohio' in frame3.columns

True

In [105]:
2003 in frame3.index

False

# Reindexing

In [106]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [107]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [108]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [109]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [110]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [111]:
obj3.reindex(range(6), method='ffill') # forward filling missing data

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [112]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
   ....:                      columns=['Ohio', 'Texas', 'California'])

In [113]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [114]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [115]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [116]:
states = ['Texas', 'Utah', 'California']

In [117]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [118]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

# Dropping entries from an axis

In [120]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [123]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [121]:
new_obj = obj.drop('c')

In [122]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [124]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])

In [125]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [126]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [131]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [132]:
obj.drop('c', inplace=True)

In [133]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [135]:
data.drop(['two', 'four'], axis=1, inplace=True)

In [136]:
data

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

# Indexing, selection, and filtering

In [137]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [141]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [138]:
obj['b']

1.0

In [139]:
obj[1]

1.0

In [140]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [142]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [143]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [144]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [145]:
obj['b':'c'] #Slicing with labels behaves differently than normal Python slicing in that the endpoint is inclusive:

b    1.0
c    2.0
dtype: float64

In [146]:
obj['b':'c'] = 5 #Setting using these methods modifies the corresponding section of the Series:

In [147]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [148]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])

In [149]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data1 = data.T

In [152]:
data1.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [156]:
data['two'] #to select columns

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [154]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [157]:
data[:2] #to select rows

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [159]:
data[data['four'] < 10]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [160]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [161]:
data[data < 5] = 0

In [162]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data.loc['Colorado', ['two', 'three']] # to select a subset of the rows and columns from
                                       # a DataFrame with NumPy-like notation using either 
                                       # axis labels (loc) or integers (iloc)

two      5
three    6
Name: Colorado, dtype: int64

In [164]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [165]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [166]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [167]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

# Arithmetic and data alignment

In [172]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [173]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [174]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [175]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [176]:
s1 + s2 #The internal data alignment introduces NA values in the label locations that don’t overlap.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [177]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
   .....:                    index=['Ohio', 'Texas', 'Colorado'])

In [178]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
   .....:                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [179]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [180]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [181]:
df1 + df2 # In the case of DataFrame, alignment is performed on both the rows and the columns:

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [182]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [183]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [184]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [185]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [186]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [187]:
df1.add(df2, fill_value=0) # to fill with a special value, like 0, when an axis label is found 
                            # in one object but not the other:

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [188]:
df1.reindex(columns=df2.columns, fill_value=10)

a    b     c     d   e
0  0.0  1.0   2.0   3.0  10
1  4.0  5.0   6.0   7.0  10
2  8.0  9.0  10.0  11.0  10

In [189]:
arr = np.arange(12.).reshape((3, 4))

In [190]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [191]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [192]:
arr - arr[0] # rowwise

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [193]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
   .....:                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [194]:
series = frame.iloc[0]

In [195]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [196]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [197]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [198]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [199]:
series2

b    0
e    1
f    2
dtype: int64

In [200]:
frame - series2

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [218]:
frame.add(series, fill_value=0)

NotImplementedError: fill_value 0 not supported

In [203]:
series3 = frame['d']

In [204]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [205]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function application and mapping

In [220]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
   .....:                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [221]:
frame

b         d         e
Utah    0.886377 -0.477624 -0.945557
Ohio    0.032993  0.618770 -1.584414
Texas  -0.096493  1.681452  0.834490
Oregon -0.985361  0.744340 -0.285428

In [226]:
np.abs(frame)

b         d         e
Utah    0.886377  0.477624  0.945557
Ohio    0.032993  0.618770  1.584414
Texas   0.096493  1.681452  0.834490
Oregon  0.985361  0.744340  0.285428

In [225]:
frame['e'].abs()

Utah      0.945557
Ohio      1.584414
Texas     0.834490
Oregon    0.285428
Name: e, dtype: float64

In [227]:
np.abs(frame['d'])

Utah      0.477624
Ohio      0.618770
Texas     1.681452
Oregon    0.744340
Name: d, dtype: float64

In [249]:
frame.loc['Utah'] = frame.loc['Utah'].abs()

In [231]:
f = lambda x: x.max() - x.min()

In [232]:
frame.apply(f)

b    1.871738
d    2.159076
e    2.418903
dtype: float64

In [233]:
frame.apply(f, axis=1)

Utah      1.831934
Ohio      2.203183
Texas     1.777945
Oregon    1.729702
dtype: float64

In [250]:
frame

b         d         e
Utah    0.886377  0.477624  0.945557
Ohio    0.032993  0.618770 -1.584414
Texas  -0.096493  1.681452  0.834490
Oregon -0.985361  0.744340 -0.285428

In [236]:
np.mean(frame, axis = 1)

Utah     -0.178934
Ohio     -0.310884
Texas     0.806483
Oregon   -0.175483
dtype: float64

In [238]:
np.sum(np.sum(frame))

0.42354537316412033

In [239]:
def f(x):
   .....:     return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [240]:
frame.apply(f)

b         d         e
min -0.985361 -0.477624 -1.584414
max  0.886377  1.681452  0.834490

In [243]:
format = lambda x: '%.2f' % x

In [244]:
frame.applymap(format)

b      d      e
Utah     0.89  -0.48  -0.95
Ohio     0.03   0.62  -1.58
Texas   -0.10   1.68   0.83
Oregon  -0.99   0.74  -0.29

In [247]:
frame.iloc[1].map(format)

b     0.03
d     0.62
e    -1.58
Name: Ohio, dtype: object

In [251]:
frame['e'].map(format)

Utah       0.95
Ohio      -1.58
Texas      0.83
Oregon    -0.29
Name: e, dtype: object

# Sorting and ranking

In [253]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [254]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [255]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
   .....:                      columns=['d', 'a', 'b', 'c'])

In [256]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [257]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [258]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [259]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [260]:
obj = pd.Series([4, 7, -3, 2])

In [261]:
obj.sort_values(ascending=False)

1    7
0    4
3    2
2   -3
dtype: int64

In [262]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [263]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

In [264]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [266]:
frame.sort_values(by='a')

a  b
0  0  4
2  0 -3
1  1  7
3  1  2

In [267]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [268]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [269]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [270]:
obj.rank() # the order is [-5, 0, 2, 4, 4, 7, 7], so -5 is ranked 1, 0 is 2, 2 is 3, 
           # 4 is in places 4 and 5, so is ranked 4.5, same with 7

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [271]:
obj.rank(method='first') # Ranks can also be assigned according to the order they’re observed in the data:

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [272]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [273]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
   .....:                       'c': [-2, 5, 8, -2.5]})

In [274]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [275]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

# Axis indexes with duplicate values

In [277]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [278]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [279]:
obj.index.is_unique

False

In [280]:
obj['a']

a    0
a    1
dtype: int64

In [281]:
obj['c']

4

In [282]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [283]:
df

0         1         2
a  1.985020 -0.944475  0.730790
a -1.668189  0.984839  1.750123
b -1.530182 -1.010835  0.726836
b  0.331863 -0.562640  1.258838

In [284]:
df.loc['b']

0         1         2
b -1.530182 -1.010835  0.726836
b  0.331863 -0.562640  1.258838

# Summarizing and Computing Descriptive Statistics

In [285]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
   .....:                    [np.nan, np.nan], [0.75, -1.3]],
   .....:                   index=['a', 'b', 'c', 'd'],
   .....:                   columns=['one', 'two'])

In [286]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [287]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [290]:
np.sum(df, axis=1) # sums all the NaNs as 0

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [288]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
# to give NaN for the sum of all NaNs

def nansumwrapper(a, **kwargs):
    if np.isnan(a).all():
        return np.nan
    else:
        return np.nansum(a, **kwargs)

a = np.array([np.nan, np.nan])
b = np.array([np.nan, 1., 2.])


nansumwrapper(a)
# nan

nansumwrapper(b)
# 3.0

In [292]:
df.mean() # doesn't take NaNs into account

one    3.083333
two   -2.900000
dtype: float64

In [293]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [294]:
df.mean(axis=1) # only if all are NaNs the mean is a NaN

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [295]:
df.idxmax() # index value where the maximum values are attained:

one    b
two    d
dtype: object

In [296]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [297]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [298]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [299]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [300]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

# Correlation and Covariance

In [304]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues


In [305]:
import fix_yahoo_finance

ModuleNotFoundError: No module named 'fix_yahoo_finance'

# Unique Values, Value Counts, and Membership

In [306]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [307]:
uniques = obj.unique()

In [308]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [309]:
uniques.sort()

In [310]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [311]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [312]:
pd.value_counts(obj.values, sort=False)

a    3
c    3
d    1
b    2
dtype: int64

In [313]:
mask = obj.isin(['b', 'c'])

In [314]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [315]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [316]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [317]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [318]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [319]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [320]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
   .....:                      'Qu2': [2, 3, 1, 2, 3],
   .....:                      'Qu3': [1, 5, 2, 4, 4]})

In [321]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [322]:
result = data.apply(pd.value_counts).fillna(0) # calculates how many times each value appears in each column

In [323]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [325]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [326]:
df = pd.read_csv('examples/ex1.csv')

In [327]:
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [328]:
pd.read_table('examples/ex1.csv', sep=',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

# Reading and Writing Data in Text Format

In [329]:
!cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [330]:
pd.read_csv('examples/ex2.csv', header=None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [331]:
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [333]:
names = ['a', 'b', 'c', 'd', 'message']

In [334]:
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [1]:
!cat examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16


In [5]:
parsed = pd.read_csv('examples/csv_mindex.csv', index_col=['key1', 'key2'])

In [6]:
parsed

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [7]:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [8]:
result = pd.read_table('examples/ex3.txt', sep='\s+')

In [9]:
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [10]:
!cat examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [11]:
pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
!cat examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [13]:
result = pd.read_csv('examples/ex5.csv')

In [14]:
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [15]:
pd.isnull(result)

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [16]:
result = pd.read_csv('examples/ex5.csv', na_values=['NULL'])

In [17]:
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [18]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']} # Different NA sentinels 
                                                            #can be specified for each column in a dict

In [19]:
pd.read_csv('examples/ex5.csv', na_values=sentinels)

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

# Reading Text Files in Pieces

In [21]:
result = pd.read_csv('examples/ex6.csv')

In [22]:
pd.options.display.max_rows = 10  # Make display more compact

In [23]:
result

one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [24]:
pd.read_csv('examples/ex6.csv', nrows=5) # to read only 5 rows

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [25]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000) # To read out a file in pieces, 
                                                            #specify a chunksize as a number of rows:

In [26]:
chunker

In [27]:
# The TextParser object returned by read_csv allows you to iterate over 
# the parts of the file according to the chunksize. For example, we can 
# iterate over ex6.csv, aggregating the value counts in the 'key' column like so:

chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

In [28]:
tot

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
     ...  
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

# Writing Data Out to Text Format

In [29]:
data = pd.read_csv('examples/ex5.csv')

In [30]:
data

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [31]:
data.to_csv('examples/out.csv')

In [32]:
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo


In [33]:
import sys # writing to sys.stdout so it prints the text result to the console

In [34]:
data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo


In [35]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo


In [36]:
data.to_csv(sys.stdout, index=False, header=False) # disable writing columns and rows labels

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo


In [37]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c']) # to write only a subset of the 
                                                            # columns, and in an order of your choosing:

a,b,c
1,2,3.0
5,6,
9,10,11.0


In [38]:
dates = pd.date_range('1/1/2000', periods=7)

In [39]:
ts = pd.Series(np.arange(7), index=dates)

In [40]:
ts.to_csv('examples/tseries.csv')

In [41]:
!cat examples/tseries.csv

2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6


# Manually Working with Delimited Formats

In [42]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"


In [43]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)

In [44]:
for line in reader:
   ....:     print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


In [46]:
lines = list(csv.reader(open('examples/ex7.csv')))

In [47]:
header, values = lines[0], lines[1:]

In [48]:
data_dict = {h: v for h, v in zip(header, zip(*values))}

In [49]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [50]:
# Defining a new format with a different delimiter, string quoting convention, or line terminator

class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL
reader = csv.reader(f, dialect=my_dialect)

In [51]:
# Individual CSV dialect parameters can also be given 
# as keywords to csv.reader without having to define a subclass:

reader = csv.reader(f, delimiter='|')

In [52]:
# To write delimited files manually, you can use csv.writer. 
# It accepts an open, writable file object and the

with open('mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))