In [1]:
# Populating the interactive namespace from pandas, numpy, matplotlib and scipy
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

# Magnitude sampling

In [2]:
# defining the parameters for Gutenberg-Richter, beta:
beta = 2.13

In [11]:
# defining the parameters for Gutenberg-Richter, annual occurrence rate of earthquakes wit M>=4.3:
fn43 = 22.189

In [23]:
# annual occurrence rate of earthquakes with M>=6.5, given by truncated Gutenberg-Richter:
M65 = fn43*(1 - (1 - np.exp(-beta*(6.5 - 4.3)))/
                (1 - np.exp(-beta*(8.7 - 4.3))))

In [24]:
M65

0.20278995113008463

In [25]:
# number of earthquakes with M>=6.5 in 100000 years, given by truncated Gutenberg-Richter:
M65*100000

20278.995113008463

In [15]:
# annual occurrence rate of earthquakes with M>=7, given by truncated Gutenberg-Richter:
M7 = fn43*(1 - (1 - np.exp(-beta*(7 - 4.3)))/
                (1 - np.exp(-beta*(8.6 - 4.3))))

In [16]:
M7

0.068223523260349805

In [17]:
# number of earthquakes with M>=7 in 100000 years, given by truncated Gutenberg-Richter:
M7*100000

6822.3523260349803

In [18]:
# defining minimum and maximum earthquake magnitudes 
Mmin = 7
Mmax = 8.6

In [29]:
int(round((Mmax - Mmin)/0.1 + 1))

17

In [72]:
# creating vector of magnitudes with 0.1 step
m = np.around(np.array([Mmin + 0.1*i for i in range(0, int(round((Mmax - Mmin)/0.1 + 1)))]),1)

In [73]:
m

array([ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,
        8.1,  8.2,  8.3,  8.4,  8.5,  8.6])

In [164]:
# calculating cumulative annual occurrence rate of earthquakes of all the magnitudes, given by truncated Gutenberg-Richter:
CNM = fn43*(1 - (1 - np.exp(-beta*(m - 4.3)))/
                (1 - np.exp(-beta*(8.7 - 4.3))))

In [165]:
# cumulative recurrence time
1/CNM

array([   14.56233812,    18.13758047,    22.627083  ,    28.28522401,
          35.44905093,    44.57220097,    56.27708361,    71.43809278,
          91.31998024,   117.81967374,   153.91503174,   204.56204974,
         278.66849725,   394.02796703,   592.12231159,   997.33237334,
        2231.4161443 ])

In [166]:
# cumulative number of earthquakes in 100000 years
CNM*100000

array([ 6867.02912679,  5513.41454718,  4419.48261724,  3535.41481437,
        2820.94999375,  2243.55086415,  1776.92221394,  1399.81340647,
        1095.05060932,   848.7546844 ,   649.70912111,   488.84922755,
         358.84931734,   253.78909206,   168.88402623,   100.26747619,
          44.81459017])

In [169]:
# calculating number of earthquakes of each magnitude in 100000 years
NM = np.zeros(len(CNM))
CNM = CNM*100000
NM[len(CNM) - 1] = CNM[len(CNM) - 1]
for i in range(len(CNM)-1):
               NM[i] = CNM[i] - CNM[i+1]

In [170]:
NM # number of earthquakes of each magnitude in 100000 years

array([ 1353.61457961,  1093.93192994,   884.06780288,   714.46482061,
         577.3991296 ,   466.62865021,   377.10880747,   304.76279715,
         246.29592492,   199.04556329,   160.85989356,   129.99991021,
         105.06022528,    84.90506583,    68.61655003,    55.45288603,
          44.81459017])

In [92]:
counts

array([1348, 1124,  868,  675,  607,  470,  364,  300,  245,  218,  172,
        114,  114,   87,   66,   56,   39])

In [58]:
np.sum(NM/np.sum(NM))

1.0

In [171]:
# probability of occurrence of earthquake of each magnitude
PNM = NM/np.sum(NM)

In [172]:
PNM

array([ 0.19711793,  0.15930207,  0.12874094,  0.10404278,  0.08408281,
        0.06795204,  0.05491586,  0.04438059,  0.03586645,  0.02898569,
        0.02342496,  0.01893103,  0.01529923,  0.01236416,  0.00999217,
        0.00807524,  0.00652605])

In [56]:
CNM

array([ 0.06867029,  0.05513415,  0.04419483,  0.03535415,  0.0282095 ,
        0.02243551,  0.01776922,  0.01399813,  0.01095051,  0.00848755,
        0.00649709,  0.00488849,  0.00358849,  0.00253789,  0.00168884,
        0.00100267,  0.00044815])

In [125]:
# calculating vector of magnitudes by random sampling with replacement (Monte Carlo) using
# the probabilities calculated by Gutenberg Richter, 1 mln years
magnitudes = np.random.choice(m, 68670, replace=True, p = PNM)

In [90]:
magnitudes

array([ 7.2,  7.7,  7.2, ...,  7.2,  7.4,  7.5])

In [126]:

unique, counts = np.unique(magnitudes, return_counts=True)

In [81]:
counts

array([1353, 1084,  885,  725,  584,  463,  358,  327,  250,  198,  151,
        129,  106,   66,   79,   64,   45])

In [98]:
counts/34335/PNM

array([ 0.99216255,  0.99129075,  0.99540299,  1.00439241,  0.97991557,
        1.02180186,  1.03471902,  1.0283451 ,  0.95738896,  1.02188092,
        1.02698502,  0.99846646,  1.0508303 ,  0.97756655,  1.00267781,
        0.948557  ,  1.04430719])

In [95]:
6867*5

34335

In [108]:
# probability of occurrence of earthquake of each magnitude calculated using Monte Carlo relative to 
# probability calculated from Gutenberg-Richter, 100000 years
counts/6867/PNM

array([ 1.00102774,  0.98452613,  1.06892707,  1.00215296,  1.01490019,
        1.03508871,  0.94933216,  0.94500124,  0.958201  ,  0.94451137,
        1.05060816,  1.01538962,  0.91376548,  1.04823401,  0.90357593,
        0.93773696,  0.78099896])

In [113]:
# probability of occurrence of earthquake of each magnitude calculated using Monte Carlo relative to 
# probability calculated from Gutenberg-Richter, 1000000 years
counts/68670/PNM

array([ 0.99120216,  1.0049114 ,  0.99540299,  1.00873134,  1.00468191,
        0.99865702,  0.9692204 ,  0.99947006,  1.0142314 ,  1.0424793 ,
        1.04003991,  0.96385091,  1.01370858,  1.04234505,  0.9283514 ,
        1.01888727,  0.98182727])

In [127]:
# difference between the two probabilites (in percents), 1 mln years
np.around((1 - counts/68670/PNM)*100, 2)

array([ 0.38, -1.29, -0.82,  0.32,  0.83, -1.43,  1.2 ,  0.41,  2.03,
        1.98,  0.47, -1.39, -1.66,  3.89,  0.61, -0.45,  0.92])

In [128]:
# mean difference between the two probabilites (in percents), 1 mln years
np.mean(abs(np.around((1 - counts/68670/PNM)*100, 2)))

1.1811764705882355

In [119]:
# difference between the two probabilites (in percents), 100000 years
np.around((1 - counts/6867/PNM)*100, 2)

array([ -4.54,   0.72,   1.25,   0.2 ,  -1.14,   4.21,   0.82,   7.47,
         8.24,  -7.01,  -8.79,  -7.69,   8.62,  12.84,   9.64,  -6.4 ,
        -7.11])

In [120]:
# mean difference between the two probabilites (in percents), 100000 years
np.mean(abs(np.around((1 - counts/6867/PNM)*100, 2)))

5.6876470588235293

In [234]:
# calculating mean difference and std between the two probabilites (in percents), 100000 years
# 100 Monte Carlo runs
meanerror5 = np.zeros(100)
std5 = np.zeros(100)
maxerror5 = np.zeros(100)
for i in range(len(meanerror5)):
    magnitudes = np.random.choice(m, 6867, replace=True, p = PNM)
    unique, counts = np.unique(magnitudes, return_counts=True)
    meanerror5[i] = np.mean(abs(np.around((1 - counts/6867/PNM)*100, 2)))
    maxerror5[i] = np.max(abs(np.around((1 - counts/6867/PNM)*100, 2)))
    std5[i] = np.std(abs(np.around((1 - counts/6867/PNM)*100, 2)))

In [235]:
# mean difference between the two probabilites (in percents), 100000 years
# 100 Monte Carlo runs
np.mean(meanerror5)

5.7512352941176479

In [236]:
np.std(meanerror5)

1.2267917889461135

In [237]:
# mean std of the differences between the two probabilites (in percents), 100000 years
# 100 Monte Carlo runs
np.mean(std5)

5.5307371883911358

In [238]:
np.std(std5)

1.622775927243423

In [240]:
np.max(maxerror5)

49.509999999999998

In [207]:
std5

array([ 3.94569144,  4.26988375,  6.1008693 ,  7.94746196,  6.08458589,
        4.42936263,  4.03479417,  2.61274134,  4.7212823 ,  6.88571502,
        4.49607872,  7.29212368,  7.22717818,  3.69853857,  3.85701814,
        4.94854528,  3.16406565,  7.22361041,  4.88061578,  5.31238014,
        2.89970193,  7.27609144,  3.95283587,  6.19293978,  4.38185627,
        4.58797526,  5.62783302,  4.21893737,  4.38833749,  5.58506647,
        6.9914448 ,  4.9269952 ,  6.55941074,  6.85219052,  5.0119777 ,
        6.45666684,  3.52755549,  3.86841849,  5.82917302,  6.4497857 ,
        4.31265323,  5.63236022,  3.88751555,  4.06824218,  8.15209239,
        6.57363408,  6.50062451,  7.44338233,  7.36938463,  4.57814879,
        4.816919  ,  4.40678119,  6.02615671,  5.39252834,  2.43446448,
        6.58398792,  5.18260152,  4.51511564,  5.94044072,  3.52990585,
        7.00739283,  8.64167724,  3.83313996,  4.81601193,  4.01318545,
        5.92414057,  8.12313608,  3.25527541,  6.09839539,  3.61

In [208]:
meanerror5

array([ 4.97882353,  4.02470588,  5.71764706,  7.45117647,  6.18294118,
        5.17764706,  5.62352941,  3.23058824,  5.78588235,  6.54411765,
        5.66235294,  5.49705882,  6.43117647,  5.32647059,  5.54588235,
        5.57235294,  3.93058824,  6.82764706,  4.35117647,  7.16235294,
        3.63588235,  7.09588235,  4.83058824,  6.34294118,  3.64941176,
        5.76647059,  6.94882353,  5.18705882,  5.44      ,  5.99823529,
        6.82764706,  6.27352941,  5.99882353,  5.86705882,  5.10823529,
        7.45058824,  4.80588235,  4.68176471,  6.77352941,  5.98764706,
        6.19470588,  4.76647059,  5.35411765,  3.69235294,  6.00882353,
        6.76764706,  5.49529412,  4.65647059,  7.26764706,  5.33647059,
        5.45176471,  5.56823529,  5.2       ,  7.06705882,  2.88941176,
        6.09176471,  5.46058824,  4.48117647,  5.94588235,  4.41      ,
        7.18529412,  7.48294118,  3.80705882,  5.76235294,  5.46882353,
        5.59764706,  6.41882353,  3.82764706,  5.14823529,  5.20

In [219]:
# calculating mean difference and std between the two probabilites (in percents), 1 mln years
# 100 Monte Carlo runs
meanerror6 = np.zeros(100)
std6 = np.zeros(100)
maxerror6 = np.zeros(100)
for i in range(len(meanerror5)):
    magnitudes = np.random.choice(m, 68670, replace=True, p = PNM)
    unique, counts = np.unique(magnitudes, return_counts=True)
    meanerror6[i] = np.mean(abs(np.around((1 - counts/68670/PNM)*100, 2)))
    maxerror6[i] = np.max(abs(np.around((1 - counts/68670/PNM)*100, 2)))
    std6[i] = np.std(abs(np.around((1 - counts/68670/PNM)*100, 2)))

In [220]:
# mean difference between the two probabilites (in percents), 1 mln years
# 100 Monte Carlo runs
np.mean(meanerror6)

1.8309235294117645

In [221]:
# mean std of the differences between the two probabilites (in percents), 1 mln years
# 100 Monte Carlo runs
np.mean(std6)

1.701805719177409

In [222]:
np.std(meanerror6)

0.39064925333980627

In [223]:
np.std(std6)

0.4675239054139802

In [226]:
np.max(maxerror6)

11.57

In [299]:
def fault_size(a,b):
    par = np.around(10**(a + b*m), 0)
    par = [int(i) for i in par]
    return par

In [302]:
Lrf = fault_size(-2.693,0.614)
Lsi = fault_size(-2.412,0.583)
Lnf = fault_size(-1.722,0.485)
Lss = fault_size(-2.943,0.681)
LdsP = fault_size(-2.19,0.55)
LB = fault_size(-2.37,0.57)
LSor = fault_size(-2.44,0.59)
LSorSS = fault_size(-2.57,0.62)
LSorR = fault_size(-2.42,0.58)
LSorN = fault_size(-1.88,0.5)

In [303]:
Length = pd.DataFrame(np.column_stack([Lrf, Lsi, Lnf, Lss, LdsP, LB, LSor, LSorSS, LSorR, LSorN]), index = m, 
                     columns = ['RF Thin', 'SI Thin', 'NF Thin', 'SS Thin', 'DS Pap', 'Blaser', 'All Wells', 
                                'SS Wells', 'RF Wells', 'NF Wells'])

In [304]:
Length

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0       40       47       47       67      46      42         49        59   
7.1       46       53       53       78      52      48         56        68   
7.2       53       61       59       91      59      54         64        78   
7.3       62       70       66      107      67      62         74        90   
7.4       71       80       74      125      76      70         84       104   
7.5       82       91       82      146      86      80         97       120   
7.6       94      104       92      171      98      92        111       139   
7.7      108      119      103      200     111     104        127       160   
7.8      125      137      115      234     126     119        145       185   
7.9      144      156      129      273     143     136        166       213   
8.0      166      179      144      320     162     155        191       245   
8.1      191      204      161      374     184     177        218       283   
8.2      220      234      180      438     209     201        250       327   
8.3      253      267      201      512     237     230        286       377   
8.4      291      306      225      599     269     262        328       435   
8.5      336      350      251      701     305     299        376       501   
8.6      387      400      281      820     347     340        431       578   

     RF Wells  NF Wells  
7.0        44        42  
7.1        50        47  
7.2        57        52  
7.3        65        59  
7.4        74        66  
7.5        85        74  
7.6        97        83  
7.7       111        93  
7.8       127       105  
7.9       145       117  
8.0       166       132  
8.1       190       148  
8.2       217       166  
8.3       248       186  
8.4       283       209  
8.5       324       234  
8.6       370       263

In [298]:
Length.iloc[::2, :]

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0       40       47       47       67      46      42         49        59   
7.2       53       61       59       91      59      54         64        78   
7.4       71       80       74      125      76      70         84       104   
7.6       94      104       92      171      98      92        111       139   
7.8      125      137      115      234     126     119        145       185   
8.0      166      179      144      320     162     155        191       245   
8.2      220      234      180      438     209     201        250       327   
8.4      291      306      225      599     269     262        328       435   
8.6      387      400      281      820     347     340        431       578   

     RF Wells  NF Wells  
7.0        44        42  
7.2        57        52  
7.4        74        66  
7.6        97        83  
7.8       127       105  
8.0       166       132  
8.2       217       166  
8.4       283       209  
8.6       370       263

In [305]:
Wrf = fault_size(-1.669,0.435)
Wsi = fault_size(-0.88,0.366)
Wnf = fault_size(-0.829,0.323)
Wss = fault_size(-0.543,0.261)
WdsP = fault_size(-0.63,0.31)
WB = fault_size(-1.86,0.46)
WSor = fault_size(-1.01,0.32)
WSorSS = fault_size(-0.76,0.27)
WSorR = fault_size(-1.61,0.41)
WSorN = fault_size(-1.14,0.35)

In [306]:
Width = pd.DataFrame(np.column_stack([Wrf, Wsi, Wnf, Wss, WdsP, WB, WSor, WSorSS, WSorR, WSorN]), index = m, 
                     columns = ['RF Thin', 'SI Thin', 'NF Thin', 'SS Thin', 'DS Pap', 'Blaser', 'All Wells', 
                                'SS Wells', 'RF Wells', 'NF Wells'])

In [307]:
Width.iloc[::2, :]

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0       24       48       27       19      35      23         17        13   
7.2       29       57       31       22      40      28         20        15   
7.4       35       67       36       24      46      35         23        17   
7.6       43       80       42       28      53      43         26        20   
7.8       53       94       49       31      61      53         31        22   
8.0       65      112       57       35      71      66         35        25   
8.2       79      132       66       40      82      82         41        28   
8.4       97      156       77       45      94     101         48        32   
8.6      118      185       89       50     109     125         55        36   

     RF Wells  NF Wells  
7.0        18        20  
7.2        22        24  
7.4        27        28  
7.6        32        33  
7.8        39        39  
8.0        47        46  
8.2        56        54  
8.4        68        63  
8.6        82        74

In [308]:
10.7*1.5

16.049999999999997

In [331]:
M0 = 10**(1.5*m + 9.05)

In [333]:
M0/3.3/(10**16)

array([   1075.19208859,    1518.74919281,    2145.29025571,
          3030.3030303 ,    4280.41680189,    6046.2494393 ,
          8540.55433716,   12063.85365314,   17040.64621789,
         24070.5525674 ,   34000.55922127,   48027.06643822,
         67840.03450207,   95826.59576268,  135358.66428817,
        191199.19529703,  270076.04185871])

In [321]:
10**(1.5*8.8 + 16.1)/440000/140000/10.67

3.0356721645968474e+17

In [335]:
M0[0]/3.3/(10**16)/Length.iloc[0,:]

RF Thin      26.879802
SI Thin      22.876427
NF Thin      22.876427
SS Thin      16.047643
DS Pap       23.373741
Blaser       25.599812
All Wells    21.942696
SS Wells     18.223595
RF Wells     24.436184
NF Wells     25.599812
Name: 7.0, dtype: float64

In [324]:
10**(1.5*8.6 + 9.05)/19462/3.3/(10**16)

13.877095974653702

In [344]:
M0[0]/3.3/(10**16)/A.iloc[0,:]

RF Thin      1.119992
SI Thin      0.476592
NF Thin      0.847275
SS Thin      0.844613
DS Pap       0.667821
Blaser       1.113035
All Wells    1.290747
SS Wells     1.401815
RF Wells     1.357566
NF Wells     1.279991
Name: 7.0, dtype: float64

In [339]:
(Width*Length).iloc[0,:]

RF Thin       960
SI Thin      2256
NF Thin      1269
SS Thin      1273
DS Pap       1610
Blaser        966
All Wells     833
SS Wells      767
RF Wells      792
NF Wells      840
Name: 7.0, dtype: int64

In [342]:
A = Width*Length

In [343]:
A

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0      960     2256     1269     1273    1610     966        833       767   
7.1     1196     2756     1537     1560    1924    1200       1008       952   
7.2     1537     3477     1829     2002    2360    1512       1280      1170   
7.3     1984     4340     2244     2461    2881    1922       1554      1440   
7.4     2485     5360     2664     3000    3496    2450       1932      1768   
7.5     3198     6643     3198     3796    4300    3120       2425      2160   
7.6     4042     8320     3864     4788    5194    3956       2886      2780   
7.7     5184    10353     4738     5800    6327    4992       3556      3360   
7.8     6625    12878     5635     7254    7686    6307       4495      4070   
7.9     8496    16068     6837     9009    9438    8024       5478      5112   
8.0    10790    20048     8208    11200   11502   10230       6685      6125   
8.1    13752    24888     9821    13838   13984   12921       8284      7641   
8.2    17380    30888    11880    17520   17138   16482      10250      9156   
8.3    22011    38448    14271    21504   20856   20930      12584     11310   
8.4    28227    47736    17325    26955   25286   26462      15744     13920   
8.5    35952    59500    20833    32947   30805   33488      19176     17034   
8.6    45666    74000    25009    41000   37823   42500      23705     20808   

     RF Wells  NF Wells  
7.0       792       840  
7.1      1000      1034  
7.2      1254      1248  
7.3      1560      1534  
7.4      1998      1848  
7.5      2465      2294  
7.6      3104      2739  
7.7      3885      3348  
7.8      4953      4095  
7.9      6235      4914  
8.0      7802      6072  
8.1      9690      7400  
8.2     12152      8964  
8.3     15376     10788  
8.4     19244     13167  
8.5     24300     15912  
8.6     30340     19462

In [347]:
Slip = pd.DataFrame(np.zeros((17,10)), index = m, 
                     columns = ['RF Thin', 'SI Thin', 'NF Thin', 'SS Thin', 'DS Pap', 'Blaser', 'All Wells', 
                                'SS Wells', 'RF Wells', 'NF Wells'])

In [356]:
for i in range(len(m)):
    Slip.iloc[i,:] = M0[i]/3.3/(10**16)/A.iloc[i,:]

In [359]:
Slip = np.around(Slip,2)

In [362]:
Slip

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0     1.12     0.48     0.85     0.84    0.67    1.11       1.29      1.40   
7.1     1.27     0.55     0.99     0.97    0.79    1.27       1.51      1.60   
7.2     1.40     0.62     1.17     1.07    0.91    1.42       1.68      1.83   
7.3     1.53     0.70     1.35     1.23    1.05    1.58       1.95      2.10   
7.4     1.72     0.80     1.61     1.43    1.22    1.75       2.22      2.42   
7.5     1.89     0.91     1.89     1.59    1.41    1.94       2.49      2.80   
7.6     2.11     1.03     2.21     1.78    1.64    2.16       2.96      3.07   
7.7     2.33     1.17     2.55     2.08    1.91    2.42       3.39      3.59   
7.8     2.57     1.32     3.02     2.35    2.22    2.70       3.79      4.19   
7.9     2.83     1.50     3.52     2.67    2.55    3.00       4.39      4.71   
8.0     3.15     1.70     4.14     3.04    2.96    3.32       5.09      5.55   
8.1     3.49     1.93     4.89     3.47    3.43    3.72       5.80      6.29   
8.2     3.90     2.20     5.71     3.87    3.96    4.12       6.62      7.41   
8.3     4.35     2.49     6.71     4.46    4.59    4.58       7.61      8.47   
8.4     4.80     2.84     7.81     5.02    5.35    5.12       8.60      9.72   
8.5     5.32     3.21     9.18     5.80    6.21    5.71       9.97     11.22   
8.6     5.91     3.65    10.80     6.59    7.14    6.35      11.39     12.98   

     RF Wells  NF Wells  
7.0      1.36      1.28  
7.1      1.52      1.47  
7.2      1.71      1.72  
7.3      1.94      1.98  
7.4      2.14      2.32  
7.5      2.45      2.64  
7.6      2.75      3.12  
7.7      3.11      3.60  
7.8      3.44      4.16  
7.9      3.86      4.90  
8.0      4.36      5.60  
8.1      4.96      6.49  
8.2      5.58      7.57  
8.3      6.23      8.88  
8.4      7.03     10.28  
8.5      7.87     12.02  
8.6      8.90     13.88

In [363]:
Slip.iloc[::2, :]

RF Thin  SI Thin  NF Thin  SS Thin  DS Pap  Blaser  All Wells  SS Wells  \
7.0     1.12     0.48     0.85     0.84    0.67    1.11       1.29      1.40   
7.2     1.40     0.62     1.17     1.07    0.91    1.42       1.68      1.83   
7.4     1.72     0.80     1.61     1.43    1.22    1.75       2.22      2.42   
7.6     2.11     1.03     2.21     1.78    1.64    2.16       2.96      3.07   
7.8     2.57     1.32     3.02     2.35    2.22    2.70       3.79      4.19   
8.0     3.15     1.70     4.14     3.04    2.96    3.32       5.09      5.55   
8.2     3.90     2.20     5.71     3.87    3.96    4.12       6.62      7.41   
8.4     4.80     2.84     7.81     5.02    5.35    5.12       8.60      9.72   
8.6     5.91     3.65    10.80     6.59    7.14    6.35      11.39     12.98   

     RF Wells  NF Wells  
7.0      1.36      1.28  
7.2      1.71      1.72  
7.4      2.14      2.32  
7.6      2.75      3.12  
7.8      3.44      4.16  
8.0      4.36      5.60  
8.2      5.58      7.57  
8.4      7.03     10.28  
8.6      8.90     13.88

In [369]:
578/263

2.197718631178707

In [367]:
(132-28)/28*100

371.42857142857144

In [368]:
59/42

1.4047619047619047

In [370]:
26*40

1040